# Generated by Django 3.2.9 on 2021-11-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finansials', '0002_alter_companyincomereport_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybalancereport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_reports', to='finansials.company'),
        ),
    ]
