# Generated by Django 3.2.9 on 2021-11-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finansials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyincomestatements',
            name='report_type',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Quarterly', 'Quarterly')], max_length=9),
        ),
    ]
