# Generated by Django 3.2.9 on 2021-11-21 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finansials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyincomereport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_reports', to='finansials.company'),
        ),
    ]
