# Generated by Django 3.2.9 on 2021-11-20 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finansials', '0002_alter_companyincomestatements_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBalanceStatements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField()),
                ('report_type', models.CharField(choices=[('Annual', 'Annual'), ('Quarterly', 'Quarterly')], max_length=9)),
                ('total_assets', models.BigIntegerField()),
                ('total_current_assets', models.BigIntegerField()),
                ('cash_and_equivalents_at_carrying_value', models.BigIntegerField()),
                ('cash_and_short_term_investments', models.BigIntegerField()),
                ('inventory', models.BigIntegerField()),
                ('current_ner_receivables', models.BigIntegerField()),
                ('total_non_current_assets', models.BigIntegerField()),
                ('property_plant_equipment', models.BigIntegerField()),
                ('accumulated_depreciation_amortization_ppe', models.BigIntegerField()),
                ('intangible_assets', models.BigIntegerField()),
                ('intangible_assets_excluding_goodwill', models.BigIntegerField()),
                ('goodwill', models.BigIntegerField()),
                ('investments', models.BigIntegerField()),
                ('long_term_investments', models.BigIntegerField()),
                ('short_term_investments', models.BigIntegerField()),
                ('other_current_assets', models.BigIntegerField()),
                ('other_non_current_assets', models.BigIntegerField()),
                ('total_liabilities', models.BigIntegerField()),
                ('total_current_liabilities', models.BigIntegerField()),
                ('current_accounts_payable', models.BigIntegerField()),
                ('deffered_revenue', models.BigIntegerField()),
                ('current_debt', models.BigIntegerField()),
                ('short_term_debt', models.BigIntegerField()),
                ('total_non_current_liabilities', models.BigIntegerField()),
                ('capital_lease_obligations', models.BigIntegerField()),
                ('long_term_debt', models.BigIntegerField()),
                ('current_long_term_debt', models.BigIntegerField()),
                ('long_term_debt_non_current', models.BigIntegerField()),
                ('short_long_term_debt_total', models.BigIntegerField()),
                ('other_current_liabilities', models.BigIntegerField()),
                ('other_non_current_liabilities', models.BigIntegerField()),
                ('total_shareholder_equity', models.BigIntegerField()),
                ('treasury_stock', models.BigIntegerField()),
                ('retained_earnings', models.BigIntegerField()),
                ('company_stock', models.BigIntegerField()),
                ('common_stock_sjares_outstanding', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finansials.company')),
            ],
        ),
    ]
