# Generated by Django 3.2.9 on 2021-11-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finansials', '0003_companybalancestatements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companybalancestatements',
            options={'ordering': ['date_reported']},
        ),
    ]
