# Generated by Django 3.2.9 on 2021-11-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finansials', '0004_alter_companybalancestatements_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyIncomeStatements',
            new_name='CompanyIncomeReport',
        ),
    ]
