# Generated by Django 3.2.9 on 2021-11-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finansials', '0005_rename_companyincomestatements_companyincomereport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyBalanceStatements',
            new_name='CompanyBalanceReport',
        ),
        migrations.RenameField(
            model_name='companybalancereport',
            old_name='current_ner_receivables',
            new_name='current_net_receivables',
        ),
    ]
