# Generated by Django 3.2.9 on 2021-11-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finansials', '0006_auto_20211120_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybalancereport',
            old_name='common_stock_sjares_outstanding',
            new_name='common_stock_shares_outstanding',
        ),
    ]
