# Generated by Django 3.2.9 on 2021-11-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finansials', '0007_rename_common_stock_sjares_outstanding_companybalancereport_common_stock_shares_outstanding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybalancereport',
            old_name='common_stock_shares_outstanding',
            new_name='common_stock_shares_outstanding1',
        ),
    ]
