# Generated by Django 3.2.9 on 2021-11-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finansials', '0008_rename_common_stock_shares_outstanding_companybalancereport_common_stock_shares_outstanding1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybalancereport',
            old_name='common_stock_shares_outstanding1',
            new_name='common_stock_shares_outstanding',
        ),
    ]
