# Generated by Django 4.0 on 2022-01-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tinkoff_ticker',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
