# Generated by Django 4.0 on 2022-01-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_pricepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='next_report_date',
            field=models.DateField(default='2021-01-31'),
        ),
    ]
