# Generated by Django 4.0 on 2022-01-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_company_next_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='estimated_eps',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='next_report_date',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
    ]
