# Generated by Django 4.0 on 2022-01-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_company_estimated_eps_alter_company_next_report_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricepoint',
            options={'ordering': ['date']},
        ),
    ]
